# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

schedules:
- cron: "30 14 * * 5"  # Every Friday at 2:30 PM UTC (8:00 PM IST)
  displayName: 'Weekly Friday 8 PM IST Pipeline Run'
  branches:
    include:
    - main
  always: true

# Define parameters
parameters:
  - name: buildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'Release'
    values:
    - 'Debug'
    - 'Release'

  - name: headlessMode
    displayName: 'Run tests in headless mode'
    type: boolean
    default: true

pool:
  name: 'DemoAgentPool'

variables:
  buildConfiguration: ${{ parameters.buildConfiguration }}
  # Set HEADLESS_CHROME to false by default
  HEADLESS_CHROME: 'false'

steps:
# Use a script step to set HEADLESS_CHROME based on the parameter
- script: |
    echo "Setting headless mode to: ${{ parameters.headlessMode }}"
    if [ "${{ parameters.headlessMode }}" = "true" ]; then
      echo "Setting HEADLESS_CHROME to true"
      echo "##vso[task.setvariable variable=HEADLESS_CHROME]true"
    else
      echo "Setting HEADLESS_CHROME to false"
      echo "##vso[task.setvariable variable=HEADLESS_CHROME]false"
    fi
  displayName: 'Set HEADLESS_CHROME based on input parameter'

# Run tests
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

