# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

schedules:
- cron: "30 14 * * 5"
  displayName: 'Weekly Friday 8 PM IST Pipeline Run'
  branches:
    include:
    - main
  always: false

# Define parameters
parameters:
  - name: buildConfiguration
    displayName: 'Build Configuration'
    type: string
    default: 'Release'
    values:
    - 'Debug'
    - 'Release'

  - name: headlessMode
    displayName: 'Run tests in headless mode'
    type: boolean
    default: true

pool:
  name: 'DemoAgentPool'

variables:
  buildConfiguration: ${{ parameters.buildConfiguration }}
  HEADLESS_CHROME: ${{ parameters.headlessMode }}  # Use parameter value to control headless mode

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
